### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by SupertigerDev** [avocadianmage/file-icon-info#1]
Is there anyway to make the size bigger? the quality seems to be low.

**Comment by avocadianmage** [comment]
Fixed in 921ba828ead7da2adff5ad600e11fb32a9ae2a8f

Good call. My use case had me using the images at small resolutions so I didn't notice a quality issue. This will now return base64 encoded images at 256x256 so they should be much higher quality.

**Comment by SupertigerDev** [comment]
Thanks so much. There's a big problem now >.< It doesn't seem to work anymore.

![image](https://user-images.githubusercontent.com/8193841/49002596-efa7cb00-f157-11e8-8f2a-5e32ca33305d.png)

I've tried several different exe files but it just does nothing when I run the node.
I also tried writeFileSync and remove console.log, but still didn't work.

Thanks

**Comment by avocadianmage** [comment]
Ah, I forgot to recompile the binary when publishing the package. That's what I get for only testing my C# code and not the full package 😓 

I just published v1.1.1 which has the new binary (and tested it), so things should be working now, but let me know if you still have issues.
